name: Execute Script

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Execute script
        run: script_db.js
